name: Docker Image Trii

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
    deploy:
      name: Deploy to dev
      runs-on: ubuntu-latest
      steps:
        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: danielponce
            password: 34730602Da.

        - name: check
          run: echo ${{github.sha}}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME


        - name: Deploy Docker image
          run: gcloud run deploy --image $IMAGE_NAME --region us-east1 --platform managed --port=80
